export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    RATE_LIMITED: 'TOO_MANY_REQUESTS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_FILE: 'INVALID_FILE',
    UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
    EMPTY_FILE: 'EMPTY_FILE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    PDF_EXTRACTION_FAILED: 'PDF_EXTRACTION_FAILED',
    DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND'
};

export const ERROR_CODE_STATUS_MAP = {
    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.INVALID_FILE]: 400,
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.NOT_FOUND]: 404,
    [ERROR_CODES.DOCUMENT_NOT_FOUND]: 404,
    [ERROR_CODES.FILE_TOO_LARGE]: 413,
    [ERROR_CODES.UNSUPPORTED_FORMAT]: 415,
    [ERROR_CODES.UNSUPPORTED_FORMAT]: 415,
    [ERROR_CODES.EMPTY_FILE]: 422,
    [ERROR_CODES.PDF_EXTRACTION_FAILED]: 422,
    [ERROR_CODES.RATE_LIMITED]: 429,
    [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500
};

export const UPLOAD_CONFIG = {
    MAX_FILE_SIZE_MB: Number(process.env.MAX_FILE_SIZE_MB) || 25,
    ALLOWED_MIME_TYPES: ['application/pdf'],
    DOCUMENT_TTL_MINUTES: Number(process.env.DOCUMENT_TTL_MINUTES) || 60
};

export const EXAMPLE_ENUM = {
    OPTION_A: 'option_a',
    OPTION_B: 'option_b'
};

export const DEFAULT_PORT = 4000;